; Auto-generated. Do not edit!


(cl:in-package tutorial_advanced-msg)


;//! \htmlinclude addintsFeedback.msg.html

(cl:defclass <addintsFeedback> (roslisp-msg-protocol:ros-message)
  ((process_bar
    :reader process_bar
    :initarg :process_bar
    :type cl:float
    :initform 0.0))
)

(cl:defclass addintsFeedback (<addintsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <addintsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'addintsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial_advanced-msg:<addintsFeedback> is deprecated: use tutorial_advanced-msg:addintsFeedback instead.")))

(cl:ensure-generic-function 'process_bar-val :lambda-list '(m))
(cl:defmethod process_bar-val ((m <addintsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial_advanced-msg:process_bar-val is deprecated.  Use tutorial_advanced-msg:process_bar instead.")
  (process_bar m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <addintsFeedback>) ostream)
  "Serializes a message object of type '<addintsFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'process_bar))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <addintsFeedback>) istream)
  "Deserializes a message object of type '<addintsFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'process_bar) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<addintsFeedback>)))
  "Returns string type for a message object of type '<addintsFeedback>"
  "tutorial_advanced/addintsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'addintsFeedback)))
  "Returns string type for a message object of type 'addintsFeedback"
  "tutorial_advanced/addintsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<addintsFeedback>)))
  "Returns md5sum for a message object of type '<addintsFeedback>"
  "568090721805f464e097da48cdab0d1f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'addintsFeedback)))
  "Returns md5sum for a message object of type 'addintsFeedback"
  "568090721805f464e097da48cdab0d1f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<addintsFeedback>)))
  "Returns full string definition for message of type '<addintsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 process_bar~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'addintsFeedback)))
  "Returns full string definition for message of type 'addintsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 process_bar~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <addintsFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <addintsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'addintsFeedback
    (cl:cons ':process_bar (process_bar msg))
))
