; Auto-generated. Do not edit!


(cl:in-package tutorial_advanced-msg)


;//! \htmlinclude addintsResult.msg.html

(cl:defclass <addintsResult> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type cl:integer
    :initform 0))
)

(cl:defclass addintsResult (<addintsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <addintsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'addintsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial_advanced-msg:<addintsResult> is deprecated: use tutorial_advanced-msg:addintsResult instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <addintsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial_advanced-msg:goal-val is deprecated.  Use tutorial_advanced-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <addintsResult>) ostream)
  "Serializes a message object of type '<addintsResult>"
  (cl:let* ((signed (cl:slot-value msg 'goal)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <addintsResult>) istream)
  "Deserializes a message object of type '<addintsResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<addintsResult>)))
  "Returns string type for a message object of type '<addintsResult>"
  "tutorial_advanced/addintsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'addintsResult)))
  "Returns string type for a message object of type 'addintsResult"
  "tutorial_advanced/addintsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<addintsResult>)))
  "Returns md5sum for a message object of type '<addintsResult>"
  "18df0149936b7aa95588e3862476ebde")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'addintsResult)))
  "Returns md5sum for a message object of type 'addintsResult"
  "18df0149936b7aa95588e3862476ebde")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<addintsResult>)))
  "Returns full string definition for message of type '<addintsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'addintsResult)))
  "Returns full string definition for message of type 'addintsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <addintsResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <addintsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'addintsResult
    (cl:cons ':goal (goal msg))
))
