// Generated by gencpp from file tutorial_beginner/numsResponse.msg
// DO NOT EDIT!


#ifndef TUTORIAL_BEGINNER_MESSAGE_NUMSRESPONSE_H
#define TUTORIAL_BEGINNER_MESSAGE_NUMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_beginner
{
template <class ContainerAllocator>
struct numsResponse_
{
  typedef numsResponse_<ContainerAllocator> Type;

  numsResponse_()
    : total(0)  {
    }
  numsResponse_(const ContainerAllocator& _alloc)
    : total(0)  {
  (void)_alloc;
    }



   typedef int32_t _total_type;
  _total_type total;





  typedef boost::shared_ptr< ::tutorial_beginner::numsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_beginner::numsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct numsResponse_

typedef ::tutorial_beginner::numsResponse_<std::allocator<void> > numsResponse;

typedef boost::shared_ptr< ::tutorial_beginner::numsResponse > numsResponsePtr;
typedef boost::shared_ptr< ::tutorial_beginner::numsResponse const> numsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_beginner::numsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_beginner::numsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tutorial_beginner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tutorial_beginner': ['/home/yan/ros_tutorial/src/tutorial_beginner/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_beginner::numsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_beginner::numsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_beginner::numsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_beginner::numsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_beginner::numsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_beginner::numsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_beginner::numsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "153fab1a8b8e38f159dc8686d253f2b4";
  }

  static const char* value(const ::tutorial_beginner::numsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x153fab1a8b8e38f1ULL;
  static const uint64_t static_value2 = 0x59dc8686d253f2b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_beginner::numsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_beginner/numsResponse";
  }

  static const char* value(const ::tutorial_beginner::numsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_beginner::numsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 total\n\
";
  }

  static const char* value(const ::tutorial_beginner::numsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_beginner::numsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct numsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_beginner::numsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_beginner::numsResponse_<ContainerAllocator>& v)
  {
    s << indent << "total: ";
    Printer<int32_t>::stream(s, indent + "  ", v.total);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_BEGINNER_MESSAGE_NUMSRESPONSE_H
