// Generated by gencpp from file tutorial_beginner/numsRequest.msg
// DO NOT EDIT!


#ifndef TUTORIAL_BEGINNER_MESSAGE_NUMSREQUEST_H
#define TUTORIAL_BEGINNER_MESSAGE_NUMSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_beginner
{
template <class ContainerAllocator>
struct numsRequest_
{
  typedef numsRequest_<ContainerAllocator> Type;

  numsRequest_()
    : num1(0)
    , num2(0)  {
    }
  numsRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;

   typedef int32_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::tutorial_beginner::numsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_beginner::numsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct numsRequest_

typedef ::tutorial_beginner::numsRequest_<std::allocator<void> > numsRequest;

typedef boost::shared_ptr< ::tutorial_beginner::numsRequest > numsRequestPtr;
typedef boost::shared_ptr< ::tutorial_beginner::numsRequest const> numsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_beginner::numsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_beginner::numsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tutorial_beginner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tutorial_beginner': ['/home/yan/ros_tutorial/src/tutorial_beginner/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_beginner::numsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_beginner::numsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_beginner::numsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_beginner::numsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_beginner::numsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_beginner::numsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_beginner::numsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c68f3979e1a90aac7d1c75a1096d1e60";
  }

  static const char* value(const ::tutorial_beginner::numsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc68f3979e1a90aacULL;
  static const uint64_t static_value2 = 0x7d1c75a1096d1e60ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_beginner::numsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_beginner/numsRequest";
  }

  static const char* value(const ::tutorial_beginner::numsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_beginner::numsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num1\n\
int32 num2\n\
";
  }

  static const char* value(const ::tutorial_beginner::numsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_beginner::numsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct numsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_beginner::numsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_beginner::numsRequest_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_BEGINNER_MESSAGE_NUMSREQUEST_H
