// Generated by gencpp from file tutorial_beginner/nums.msg
// DO NOT EDIT!


#ifndef TUTORIAL_BEGINNER_MESSAGE_NUMS_H
#define TUTORIAL_BEGINNER_MESSAGE_NUMS_H

#include <ros/service_traits.h>


#include <tutorial_beginner/numsRequest.h>
#include <tutorial_beginner/numsResponse.h>


namespace tutorial_beginner
{

struct nums
{

typedef numsRequest Request;
typedef numsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nums
} // namespace tutorial_beginner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorial_beginner::nums > {
  static const char* value()
  {
    return "5b345eb3e3672a43cb5b3d560a6e8961";
  }

  static const char* value(const ::tutorial_beginner::nums&) { return value(); }
};

template<>
struct DataType< ::tutorial_beginner::nums > {
  static const char* value()
  {
    return "tutorial_beginner/nums";
  }

  static const char* value(const ::tutorial_beginner::nums&) { return value(); }
};


// service_traits::MD5Sum< ::tutorial_beginner::numsRequest> should match 
// service_traits::MD5Sum< ::tutorial_beginner::nums > 
template<>
struct MD5Sum< ::tutorial_beginner::numsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial_beginner::nums >::value();
  }
  static const char* value(const ::tutorial_beginner::numsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial_beginner::numsRequest> should match 
// service_traits::DataType< ::tutorial_beginner::nums > 
template<>
struct DataType< ::tutorial_beginner::numsRequest>
{
  static const char* value()
  {
    return DataType< ::tutorial_beginner::nums >::value();
  }
  static const char* value(const ::tutorial_beginner::numsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorial_beginner::numsResponse> should match 
// service_traits::MD5Sum< ::tutorial_beginner::nums > 
template<>
struct MD5Sum< ::tutorial_beginner::numsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial_beginner::nums >::value();
  }
  static const char* value(const ::tutorial_beginner::numsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial_beginner::numsResponse> should match 
// service_traits::DataType< ::tutorial_beginner::nums > 
template<>
struct DataType< ::tutorial_beginner::numsResponse>
{
  static const char* value()
  {
    return DataType< ::tutorial_beginner::nums >::value();
  }
  static const char* value(const ::tutorial_beginner::numsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIAL_BEGINNER_MESSAGE_NUMS_H
